### ISSUE TITLE
Vue JS version 3

### ISSUE THREAD

**Issue by StefanPostma** [VPetar/vue-auth-boilerplate#2]
Hi! any plans for an upgrade to CLI v4?

**Comment by VPetar** [comment]
Heya, been off for a while, and somehow my mail client lost the mail. ^_^
I'll work on CLI v4 soon, expect a new update to master. :)

**Comment by VPetar** [comment]
@StefanPostma hello
`"@vue/cli-service": "^4.5.4"` is an installed version, did you mean perhaps an upgrade to the Vue version?

**Comment by StefanPostma** [comment]
sorry i meant Vue JS version 3 :)

**Comment by VPetar** [comment]
@StefanPostma Gotcha, I'll work on that ^_^

**Comment by VPetar** [comment]
@StefanPostma all right, this took more than I thought, sorry about that, too many things in life. :)
[vue3 branch here](https://github.com/VPetar/vue-auth-boilerplate/tree/vue3)

It's not all done, but it's usable, Vue 3 TypeScript enabled boilerplate. :)

**Comment by VPetar** [comment]
Closing the issue due to inactivity
